### ISSUE TITLE
.equals no detecta la variable char

### ISSUE THREAD

**Issue by Painiller97** [Painiller97/Ejercicios-POO#1]
En el método de comprobar consumo al intentar que el programa detecte que el consumo del objeto sea igual a las letras que pide, salta el error de "char cannot be deferenced"

**Comment by cr998** [comment]
Voy a echarle un ojo en un rato, si lo soluciono te hago pull request

**Comment by cr998** [comment]
Acabo de ver el proyecto, te comento , estabas intentado acceder al metodo .equals() sobre el tipo char y char no es un objeto si no un tipo de dato al igual que un int o un double, estos tipos de variables son tipos de datos, no objetos y no tienen métodos, para usar el método .equals() deberias usar el comparador ==, o crear un objeto de tipo Character , no usar el tipo de dato char

**Comment by Painiller97** [comment]
Ahh vale, entiendo entonces como va el char
